Fix error no template named 'raw_ptr'
../fpdfsdk/fpdf_editpage.cpp:171:3: error: no template named 'raw_ptr'
  171 |   raw_ptr<CPDF_PageObject> page_obj;
      |   ^

As far as I understand, `raw_ptr` is only defined when using partition allocator, which we disabled (#28, #124, #137, #148)