iOS: fix errors with BrowserEngine
Remove the previous workaround for BrowserEngine.
This should fix the following error:

    ld64.lld: error: undefined symbol: be_memory_inline_jit_restrict_rwx_to_rw_with_witness_impl

Disable BrowserEngineCore JIT on Catalyst
This should fix the following error:

    error: 'be_memory_inline_jit_restrict_rwx_to_rx_with_witness' is unavailable: not available on macCatalyst

These errors were likely triggered by the recent upgrade to XCode 26.0